#/usr/bin/env zsh

mkdir -p $ROOT/build/$INSTNAME
cd $_
pwd
rm -rf *
if [[ -z "${PYTHON+x}" ]]; then
  echo "Not building Python bindings"
  cmake $CMAKE_GEN $CMAKE_PLATFORM_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ROOT/install/$INSTNAME -DCMAKE_OSX_DEPLOYMENT_TARGET=$OSX_VER -DLIBSBML_LIBRARY=$LIBSBML -DLIBSBML_INCLUDE_DIR=$LIBSBML_INCLUDE -DEXTRA_LIBS='xml2;bz2;z;iconv' -DZIPPER_LIBRARY=$ZIPPER -DZIPPER_INCLUDE_DIR=$ZIPPER_INCLUDE_DIR $ROOT/src/$SRCNAME
else
  echo "Building Python bindings"
  cmake $CMAKE_GEN $CMAKE_PLATFORM_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ROOT/install/$INSTNAME -DCMAKE_OSX_DEPLOYMENT_TARGET=$OSX_VER -DLIBSBML_LIBRARY=$LIBSBML -DLIBSBML_INCLUDE_DIR=$LIBSBML_INCLUDE -DEXTRA_LIBS='xml2;bz2;z;iconv' -DZIPPER_LIBRARY=$ZIPPER -DZIPPER_INCLUDE_DIR=$ZIPPER_INCLUDE_DIR -DWITH_PYTHON=ON -DPYTHON_EXECUTABLE=$PYTHON -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE -DPYTHON_USE_DYNAMIC_LOOKUP=ON $ROOT/src/$SRCNAME
fi
eval $CMAKE_BUILD_CMD
